### ISSUE TITLE
Corrections mineures #2

### ISSUE THREAD

**Issue by flad887** [blondimi/ift436_a21#3]
Page 38: encadré

> [...] bien que des inversions aient disparu ~~es~~

Page 43: section 2.4, premier paragraphe

Il semble que les variables **t** et **u** ne soient pas définies dans le contexte. J'imagine qu'on voulait dire **x** et **y**. La lettre **t** est utilisée pour définir le temps d'exécution plus loin dans la section.

**Comment by blondimi** [comment]
C'est corrigé, merci.
